# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_windows:

    name: Build for Windows

    runs-on: windows-2019

    strategy:
      matrix:
        node-version: [14.17.6]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install packages
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
    - name: Run tests
      uses: borales/actions-yarn@v4
      with:
        cmd: test # will run `yarn test` command
    - name: Build executable
      uses: borales/actions-yarn@v4
      with:
        cmd: dist # will run `yarn dist` command

